env:
  browser: true
  es2021: true
globals:
  describe: readonly
  it: readonly
  before: readonly
  beforeEach: readonly
  after: readonly
  afterEach: readonly
extends: standard
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  'semi': 0
  'space-before-function-paren':
    - 0
    - anonymous: always
      named: always
      asyncArrow: always
